---
# defaults file for deploy
deploy_host_name: example.com

deploy_app_path: "/var/www/{{ deploy_host_name }}"

deploy_git_repo: https://github.com/wahyubucil/learn-rails.git

# What kind of environment do you use on your rails app?
# Supported environment: dotenv, figaro
deploy_rails_env: dotenv

deploy_ruby_command: "{{ ruby_rvm_install_path }}/gems/{{ ruby_version }}/wrappers/ruby"

# Supported options:
# both = Support both www and non-www
# www = Redirect non-www to www
# non-www = Redirect www to non-www
deploy_host_config: both

deploy_https: True

# Empty this if not using email reminder from letsencrypt
deploy_letsencrypt_email: ""
